# Generated by Django 3.0.4 on 2020-03-14 07:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotated_Images',
        ),
        migrations.RemoveField(
            model_name='images',
            name='id',
        ),
        migrations.AddField(
            model_name='images',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='images',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
