# Generated by Django 3.0.4 on 2020-03-24 20:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_annotation_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
