# Generated by Django 3.0.4 on 2020-03-15 22:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200314_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('annotation_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image_id', models.IntegerField()),
                ('user', models.IntegerField()),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('label', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image_source', models.URLField()),
                ('provider_id', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
