# Generated by Django 3.0.4 on 2020-03-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200315_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Image'),
        ),
    ]
